"""empty message

Revision ID: 235c3fcb22b0
Revises: 12305d37fad0
Create Date: 2021-12-03 01:50:12.031786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235c3fcb22b0'
down_revision = '12305d37fad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('external_url', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'external_url')
    # ### end Alembic commands ###
