"""empty message

Revision ID: 2d9d9fe01932
Revises: 7502df1205c7
Create Date: 2021-11-30 01:10:07.927006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d9d9fe01932'
down_revision = '7502df1205c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.drop_index('email', table_name='user')
    op.create_unique_constraint(None, 'user', ['nickname'])
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('email', 'user', ['email'], unique=False)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
