"""empty message

Revision ID: f3fa8282af7a
Revises: 2d9d9fe01932
Create Date: 2021-11-30 02:21:58.723580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fa8282af7a'
down_revision = '2d9d9fe01932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture_src', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture_src')
    # ### end Alembic commands ###
